### ISSUE TITLE
Wiki: Add OSVR (headset) instructions for Linux and Mac OS X

### ISSUE THREAD

**Issue by cvan** [Web-VR/iswebvrready#101]
à la [these instructions for OSVR (specific to Firefox now)](https://github.com/Web-VR/iswebvrready/wiki/Instructions:-OSVR)

**Comment by caseyyee** [comment]
found this on the OSVR site. 
https://github.com/OSVR/OSVR-Docs/blob/master/Integrating-Game-Engines/WebVR/webvr.md

Still needs to be tested.

**Comment by cvan** [comment]
Done: https://github.com/Web-VR/iswebvrready/wiki/Instructions:-OSVR

Yep, I copied and cleaned up the instructions from there.
