### ISSUE TITLE
How to run chromium on the VR screens?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [Web-VR/iswebvrready#114]
I have a Occulus DK2. I'm using the newest occulus app 1.1 from the official website. The occulus is working great, I am in the standard room you get spawned in and I can launch the dreamdeck demo and everything works. Now I followed the instructions on how to use the experimental chromium build, but chromium shows up on my default pc monitor, instead of the occulus. How do I see the webbrowser on the occulus?
What I did is download the browser, enable the two settings that are specified and then start the browser. Is there something more I need to do?

**Comment by cvan** [comment]
Sorry I didn't see this issue. Could you follow the instructions on WebVR Rocks for [Firefox](https://webvr.rocks/firefox) and [Chromium](https://webvr.rocks/chromium), and see if you are able to solve your problem?

If not, we can definitely carry this cover there and help you figure this out: https://github.com/webvrrocks/webvrrocks/issues/new

**Comment by Kaju-Bubanja** [comment]
It was my bad. I had the VR simulation extension for chromium enabled that's what prevented the real device to recognize that a webvr capable browser was started.
