### ISSUE TITLE
"WebVR supported, but no VRDisplays found."

### ISSUE THREAD

**Issue by VegaLay** [Web-VR/iswebvrready#115]
I have a SteamVR supported HMD but it's not a HTC Vive. It works well on OpenVR support games.

I tried the instruction for Firefox OpenVR on this web.

However it say "WebVR supported, but no VRDisplays found.".

I hope WebVR be popular.

**Comment by VegaLay** [comment]
Problem solved. 'openvr_api.dll' version was problem.

Do not download the Instructions link files.

Just put "C:\Steam\steamapps\common\SteamVR\bin\win64" path of gfx.vr.openvr-runtime

**Comment by HelenXR** [comment]
hi,@VegaLay  
If it is convenient, I have some questions to contact you through the mailbox, my mailbox is: helenhololens@gmail.com,Look forward to your reply, thank you!
