### ISSUE TITLE
Add Oculus

### ISSUE THREAD

**Issue by cvan** [Web-VR/iswebvrready#69]

**Comment by neuhaus** [comment]
care to elaborate? I'm not aware of any oculus browser

**Comment by cvan** [comment]
@neuhaus if you check [this section](https://iswebvrready.org/#oculus-rift-support), you'll see that [Chromium experimental builds](https://webvr.info/get-chrome/) and [https://nightly.mozilla.org/](Firefox Nightly) builds both support rendering of [WebVR](https://webvr.info/) pages to the Oculus Rift headset.

Here's an article my colleague on the [Mozilla VR](https://mozvr.com/) team wrote a [great article](https://blog.mozvr.com/oculus-home-rift-cv1-webvr/) documenting instructions and details of WebVR support with the Oculus Rift for both of the browsers above.

I've rewritten the instructions for all the various browsers and put them in this project's [Wiki](https://github.com/Web-VR/iswebvrready/wiki). They will be properly embedded or linked to from our various web properties very soon (https://mozvr.com/, https://iswebvrready.org/, https://aframe.io/, https://webvr.info/, etc.).

I'm closing this issue, since I did recently add the section in the platform status list for [Oculus Rift support](https://iswebvrready.org/#oculus-rift-support), but I forgot to close this issue.

Thanks, and let me know if you have any questions!
